<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="keywords" 
         content="acting school kids children academy drama classes theater play rolepaly chotabheem nayanaapte pravinbharde mataanusya mataanusayaproduction dramaproduction movieproduction serialproduction theaterproduction natak balnatak monoacting monoactingcompetetion anusaya personalitydevelopement stage">

        <meta name="description" 
         content="Mata Anusya Production - the Acting academy and Production house">
        
        <link rel="icon" href="img/logo/MataNew.png" type="image/x-icon" />
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <title>  माता अनुसया प्रॉडक्शन.      </title>
        
    


        <!-- Icon css link -->
        <link href="css/font-awesome.min.css" rel="stylesheet">
        <!-- Bootstrap -->
        <link href="css/bootstrap.min.css" rel="stylesheet">
        
        <!-- Rev slider css -->
        <link href="vendors/revolution/css/settings.css" rel="stylesheet">
        <link href="vendors/revolution/css/layers.css" rel="stylesheet">
        <link href="vendors/revolution/css/navigation.css" rel="stylesheet">
        
        <!-- Extra plugin css -->
        <link href="vendors/owl-carousel/owl.carousel.min.css" rel="stylesheet">
        
        <link href="css/style.css" rel="stylesheet">
        <link href="css/responsive.css" rel="stylesheet">
        
        <!-- Start WOW Slider.com HEAD section -->
           <link rel="stylesheet" type="text/css" href="engine1/style.css" />
           <script type="text/javascript" src="engine1/jquery.js"></script>
           
           <!-- Start cssSlider.com -->
		<!-- Generated by cssSlider.com 2.1 -->
		<link rel="stylesheet" href="cssslider_files/csss_engine1/style.css">
		<!--[if IE]><link rel="stylesheet" href="cssslider_files/csss_engine1/ie.css"><![endif]-->
		<!--[if lte IE 9]><script type="text/javascript" src="cssslider_files/csss_engine1/ie.js"></script><![endif]-->
		<script type="text/javascript" src="cssslider_files/csss_engine1/gestures.js"></script>
<!-- End WOW Slider.com HEAD section -->

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->

        <!-- custom css file -->
        <link rel="stylesheet" href="css/custom.css">
        <!-- Balnatya Slider css -->
        <link rel="stylesheet" href="css/balSlider.css">
           
    </head>
    <body>
         
        <!--================Header Menu Area =================-->
        <header class="main_menu_area">
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <a class="navbar-brand" href="#"><img height="100px" widht="120px" src="img/logo/MataNew.png" alt="Mata Anusaya Production"></a> 
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span></span>
                    <span></span>
                    <span></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav">
                        <li class="nav-item"><a class="nav-link" href="index.php"><font style="color:#847ADD">Home</font></a></li>
                        <li class="nav-item"><a class="nav-link" href="about-us.php"><font style="color:#847ADD">   आमच्या बद्दल   </font></a></li>
                        <li class="nav-item"><a class="nav-link" href="batches.php"><font style="color:#847ADD">Batches </font></a></li>
                       
                        <li class="nav-item dropdown submenu">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <font style="color:#847ADD"> 
आमचे वैशिष्टय   </font>
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li class="nav-item"><a class="nav-link" href="balnatya.php">बाल नाट्य </a></li>
                                <!--<li class="nav-item"><a class="nav-link" href="category.php?id=2"> व्यावसायिक  नाटक  </a></li>-->
                                <!--<li class="nav-item"><a class="nav-link" href="category.php?id=3">  मालीका  </a></li>-->
                                <li class="nav-item"><a class="nav-link" href="chitrapat.php">  चित्रपट  </a></li>
                                <!--<li class="nav-item"><a class="nav-link" href="category.php?id=5">Album</a></li>-->
                                <!--<li class="nav-item"><a class="nav-link" href="category.php?id=6">  स्पर्धा   </a></li>-->
                            </ul>
                        </li>
                         <li class="nav-item"><a class="nav-link" href="updates.php"><font style="color:#847ADD">Updates</font></a></li>
                        <li class="nav-item"><a class="nav-link" href="contact.php"><font style="color:#847ADD">  संपर्क साधा  </font></a></li>
                    </ul>
                </div>
            </nav>
        </header>
        